import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { useNavigate } from 'react-router-dom'
import Hospital_TokenSlip, { type TokenSlipData } from '../../components/hospital/Hospital_TokenSlip'
import { hospitalApi } from '../../utils/api'
import { previewHospitalRxPdf } from '../../utils/hospitalRxPdf'
import Toast, { type ToastState } from '../../components/ui/Toast'

function escHtml(v: any){
  return String(v ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' } as any)[c] || c)
}

function buildTokenHistoryPdfHtml({
  title,
  printedAt,
  hospital,
  filters,
  rows,
}: {
  title: string
  printedAt: Date
  hospital: { name: string; address?: string; phone?: string; logoDataUrl?: string }
  filters: string
  rows: Array<{ date?: string; time?: string; tokenNo?: string; mrNo?: string; patient?: string; phone?: string; doctor?: string; department?: string; fee?: any; isCorporate?: boolean; paidMethod?: string; status?: string }>
}){
  const printedDate = printedAt.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
  const printedTime = printedAt.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })
  const head = ['Date','Time','Type','Token #','MR #','Patient','Phone','Doctor','Department','Fee','Status']
  const th = head.map(h => `<th>${escHtml(h)}</th>`).join('')
  const body = (rows || []).map(r => {
    const method = String(r.paidMethod || '').toLowerCase()
    const t = r.isCorporate ? 'Corporate' : (method === 'bank' || method === 'card' ? 'Card' : 'Cash')
    const fee = Number(r.fee || 0)
    return `<tr>
      <td>${escHtml(r.date || '')}</td>
      <td>${escHtml(r.time || '')}</td>
      <td>${escHtml(t)}</td>
      <td>${escHtml(r.tokenNo || '')}</td>
      <td>${escHtml(r.mrNo || '')}</td>
      <td>${escHtml(r.patient || '')}</td>
      <td>${escHtml(r.phone || '')}</td>
      <td>${escHtml(r.doctor || '')}</td>
      <td>${escHtml(r.department || '')}</td>
      <td class="right">${escHtml(`Rs ${fee.toFixed(0)}`)}</td>
      <td>${escHtml(r.status || '')}</td>
    </tr>`
  }).join('')
  const empty = `<tr><td class="empty" colspan="${head.length}">No rows</td></tr>`

  return `<!doctype html>
  <html>
    <head>
      <meta charset="utf-8"/>
      <title>${escHtml(title)}</title>
      <style>
        @page { size: A4 landscape; margin: 10mm }
        *{ box-sizing:border-box }
        body{ font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial; color:#0f172a; line-height:1.35; font-size:11px }
        .header{ border:1px solid #e2e8f0; border-radius:10px; padding:12px; margin-bottom:10px }
        .hdr{ display:grid; grid-template-columns: 70px 1fr 70px; align-items:center; gap:10px }
        .logo{ width:60px; height:60px; object-fit:contain }
        .hname{ font-size:16px; font-weight:800; text-align:center }
        .hmeta{ font-size:11px; text-align:center; color:#475569 }
        .title{ margin-top:8px; font-size:14px; font-weight:800 }
        .meta{ margin-top:4px; display:flex; justify-content:space-between; gap:12px; color:#334155 }
        table{ width:100%; border-collapse:collapse; table-layout:fixed }
        th,td{ border:1px solid #e2e8f0; padding:6px 6px; vertical-align:top; word-wrap:break-word }
        th{ background:#f8fafc; font-weight:800; color:#334155 }
        td.right, th.right{ text-align:right }
        .empty{ text-align:center; color:#64748b; padding:10px }
        .footer{ margin-top:10px; color:#94a3b8; font-size:10px; text-align:center }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="hdr">
          <div>${hospital.logoDataUrl ? `<img class="logo" src="${hospital.logoDataUrl}" />` : ''}</div>
          <div>
            <div class="hname">${escHtml(hospital.name || 'Hospital')}</div>
            <div class="hmeta">${escHtml(hospital.address || '')}${hospital.phone ? ` • Ph: ${escHtml(hospital.phone)}` : ''}</div>
          </div>
          <div></div>
        </div>
        <div class="title">${escHtml(title)}</div>
        <div class="meta">
          <div><b>Filters:</b> ${escHtml(filters || '-')}</div>
          <div><b>Printed:</b> ${escHtml(printedDate)} ${escHtml(printedTime)}</div>
        </div>
      </div>

      <table>
        <thead><tr>${th}</tr></thead>
        <tbody>${body || empty}</tbody>
      </table>

      <div class="footer">Generated by Hospital Management System</div>
    </body>
  </html>`
}

interface TokenRow {
  _id: string
  date: string
  time: string
  tokenNo: string
  mrNo: string
  patient: string
  performedBy?: string
  guardianRel?: string
  guardianName?: string
  cnic?: string
  visitCategory?: 'public' | 'private'
  gender?: string
  phone?: string
  doctor?: string
  department?: string
  fee: number
  discount: number
  status: 'queued'|'in-progress'|'completed'|'returned'|'cancelled'
  paidMethod?: 'Cash'|'Bank'|'AR'|string
  isCorporate?: boolean
  corporateId?: string
  createdAt?: string
}

export default function Hospital_TokenHistory() {
  const navigate = useNavigate()
  const [query, setQuery] = useState('')
  const [rowsPerPage, setRowsPerPage] = useState(10)
  const [page, setPage] = useState(1)
  const [actioningId, setActioningId] = useState<string | null>(null)
  const [revByMethod, setRevByMethod] = useState<{ cash: number; card: number }>({ cash: 0, card: 0 })

  const today = new Date().toISOString().slice(0,10)
  const [from, setFrom] = useState(today)
  const [to, setTo] = useState(today)
  const [department, setDepartment] = useState<string>('All')
  const [doctor, setDoctor] = useState<string>('All')
  const [departments, setDepartments] = useState<any[]>([])
  const [doctors, setDoctors] = useState<any[]>([])
  const [rows, setRows] = useState<TokenRow[]>([])
  const [showSlip, setShowSlip] = useState(false)
  const [slipData, setSlipData] = useState<TokenSlipData | null>(null)
  const [toast, setToast] = useState<ToastState>(null)
  const [tokenType, setTokenType] = useState<'All' | 'Cash' | 'Corporate'>('All')
  const [visitCategory, setVisitCategory] = useState<'All' | 'Public' | 'Private'>('All')

  useEffect(() => { loadFilters() }, [])
  useEffect(() => { load() }, [from, to, department, doctor, tokenType, visitCategory])

  async function loadFilters(){
    try {
      const [deps, docs] = await Promise.all([
        hospitalApi.listDepartments() as any,
        hospitalApi.listDoctors() as any,
      ])
      setDepartments(deps.departments || [])
      setDoctors(docs.doctors || [])
    } catch {}
  }

  async function load(){
    const params: any = { from, to }
    if (department !== 'All') params.departmentId = department
    if (doctor !== 'All') params.doctorId = doctor
    const res = await hospitalApi.listTokens(params) as any
    const items: TokenRow[] = (res.tokens || []).map((t: any) => ({
      _id: t._id,
      date: t.dateIso,
      time: t.createdAt ? new Date(t.createdAt).toLocaleTimeString() : '',
      tokenNo: t.tokenNo,
      mrNo: t.patientId?.mrn || t.mrn || '-',
      patient: t.patientId?.fullName || t.patientName || '-',
      performedBy: t.createdByUsername || t.createdBy || '-',
      guardianRel: t.patientId?.guardianRel,
      guardianName: t.patientId?.fatherName,
      cnic: t.patientId?.cnicNormalized || t.patientId?.cnic,
      visitCategory: t.visitCategory,
      gender: t.patientId?.gender,
      phone: t.patientId?.phoneNormalized,
      doctor: t.doctorId?.name || '-',
      department: t.departmentId?.name || '-',
      fee: Number(t.fee || 0),
      discount: Number(t.discount || 0),
      status: t.status,
      paidMethod: t.paidMethod || t.paymentMethod || t.method,
      isCorporate: !!t.corporateId,
      corporateId: t.corporateId,
      createdAt: t.createdAt,
    }))
    const rowsClean = items.filter(r => r.status !== 'cancelled')
    setRows(rowsClean)
    setPage(1)

    // Revenue split from tokens based on selected payment method at token creation
    let cash = 0
    let card = 0
    for (const r of rowsClean){
      if (r.status === 'returned') continue
      if (r.isCorporate) continue
      const amt = Number(r.fee || 0)
      if (!isFinite(amt) || amt <= 0) continue
      const method = String(r.paidMethod || 'Cash').toLowerCase()
      if (method === 'cash') cash += amt
      else if (method === 'bank' || method === 'card') card += amt
      else card += amt
    }
    setRevByMethod({ cash, card })
  }

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    const start = new Date(from)
    const end = new Date(to)
    end.setHours(23,59,59,999)

    return rows.filter(r => {
      const d = new Date(r.date)
      if (d < start || d > end) return false
      if (department !== 'All' && r.department !== (departments.find(x=>x._id===department)?.name || r.department)) return false
      if (doctor !== 'All' && r.doctor !== (doctors.find(x=>x._id===doctor)?.name || r.doctor)) return false
      
      // Filter by token type (Cash/Corporate)
      if (tokenType === 'Corporate' && !r.isCorporate) return false
      if (tokenType === 'Cash' && r.isCorporate) return false
      
      // Filter by visit category (Public/Private)
      if (visitCategory === 'Public' && r.visitCategory === 'private') return false
      if (visitCategory === 'Private' && r.visitCategory !== 'private') return false
      
      if (!q) return true
      return [r.patient, r.mrNo, r.tokenNo, r.phone, r.doctor, r.department, r.gender, r.cnic, r.guardianName, r.guardianRel, r.time]
        .filter(Boolean)
        .some(v => String(v).toLowerCase().includes(q))
    })
  }, [query, from, to, department, doctor, rows, departments, doctors, tokenType, visitCategory])

  // Revenue only from cash tokens (exclude corporate)
  const revenueRows = useMemo(() => filtered.filter(r => r.status !== 'returned' && !r.isCorporate), [filtered])

  const totalTokens = filtered.length
  const totalRevenue = revByMethod.cash
  const cardRevenue = revByMethod.card
  const totalRevenueAll = revByMethod.cash + revByMethod.card
  const totalDiscount = revenueRows.reduce((s, r) => s + (r.discount || 0), 0)
  const returnedPatients = filtered.filter(r=>r.status==='returned').length

  async function setStatus(row: TokenRow, next: TokenRow['status']){
    try{
      setActioningId(row._id)
      await hospitalApi.updateTokenStatus(row._id, next)
      await load()
    } catch (e: any){
      setToast({ type: 'error', message: e?.message || 'Failed to update status' })
    } finally {
      setActioningId(null)
    }
  }

  function printSlip(r: TokenRow){
    const slip: TokenSlipData = {
      tokenNo: r.tokenNo,
      departmentName: r.department || '-',
      doctorName: r.doctor || '-',
      patientName: r.patient || '-',
      phone: r.phone || '',
      mrn: r.mrNo || '',
      age: undefined,
      gender: r.gender,
      guardianRel: r.guardianRel,
      guardianName: r.guardianName,
      cnic: r.cnic,
      amount: r.fee + (r.discount || 0),
      discount: r.discount || 0,
      payable: r.fee,
      createdAt: r.createdAt,
    }
    setSlipData(slip)
    setShowSlip(true)
  }

  async function printRx(r: TokenRow){
    try{
      const s: any = await hospitalApi.getSettings()
      await previewHospitalRxPdf({
        settings: {
          name: s?.settings?.name || s?.name,
          address: s?.settings?.address || s?.address,
          phone: s?.settings?.phone || s?.phone,
          logoDataUrl: s?.settings?.logoDataUrl || s?.logoDataUrl,
        },
        doctor: { name: r.doctor || '-', departmentName: r.department || '-' },
        patient: {
          name: r.patient || '-',
          mrn: r.mrNo || '-',
          gender: r.gender,
          phone: r.phone,
        },
        items: [],
        createdAt: `${r.date}T${r.time}`,
        tokenNo: r.tokenNo,
      } as any)
    } catch (e: any){
      setToast({ type: 'error', message: e?.message || 'Failed to open prescription template' })
    }
  }

  const startIdx = (page - 1) * rowsPerPage
  const pageRows = filtered.slice(startIdx, startIdx + rowsPerPage)
  const totalPages = Math.max(1, Math.ceil(filtered.length / rowsPerPage))

  const exportPdf = async () => {
    try{
      const api = (window as any).electronAPI
      if (!api || typeof api.printPreviewHtml !== 'function'){
        setToast({ type: 'error', message: 'PDF export is only available in the desktop app' })
        return
      }
      const s: any = await hospitalApi.getSettings().catch(()=>({}))
      const hospital = {
        name: s?.settings?.name || s?.name || 'Hospital',
        address: s?.settings?.address || s?.address || '',
        phone: s?.settings?.phone || s?.phone || '',
        logoDataUrl: s?.settings?.logoDataUrl || s?.logoDataUrl || '',
      }

      const depName = department === 'All'
        ? 'All Departments'
        : (departments.find((d:any)=> String(d._id||d.id) === String(department))?.name || 'Department')
      const docName = doctor === 'All'
        ? 'All Doctors'
        : (doctors.find((d:any)=> String(d._id||d.id) === String(doctor))?.name || 'Doctor')

      const filters = `From: ${from}  •  To: ${to}  •  Dept: ${depName}  •  Doctor: ${docName}  •  Type: ${tokenType}  •  Category: ${visitCategory}  •  Search: ${query || '-'}`

      const htmlDoc = buildTokenHistoryPdfHtml({
        title: 'Token History',
        printedAt: new Date(),
        hospital,
        filters,
        rows: filtered.map(r => ({
          date: r.date,
          time: r.time,
          tokenNo: r.tokenNo,
          mrNo: r.mrNo,
          patient: r.patient,
          phone: r.phone,
          doctor: r.doctor,
          department: r.department,
          fee: r.fee,
          isCorporate: r.isCorporate,
          paidMethod: r.paidMethod as any,
          status: r.status,
        })),
      })

      const r = await api.printPreviewHtml(htmlDoc, { printBackground: true, marginsType: 0 })
      if (r && r.ok === false) setToast({ type: 'error', message: r.error || 'Failed to generate PDF' })
    }catch(e: any){
      setToast({ type: 'error', message: e?.message || 'Failed to generate PDF' })
    }
  }

  function openEdit(r: TokenRow){
    // Stay on current portal (reception or hospital)
    const portal = window.location.pathname.startsWith('/reception') ? 'reception' : 'hospital'
    navigate(`/${portal}/token-generator?tokenId=${encodeURIComponent(r._id)}`)
  }

  return (
    <div>
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h2 className="text-xl font-semibold text-slate-800">Token History <span className="ml-1 rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">{filtered.length}</span></h2>
        <div className="flex flex-wrap items-center gap-2 text-sm">
          <input type="date" value={from} onChange={e=>{setFrom(e.target.value); setPage(1)}} className="rounded-md border border-slate-300 px-2 py-1" />
          <span>to</span>
          <input type="date" value={to} onChange={e=>{setTo(e.target.value); setPage(1)}} className="rounded-md border border-slate-300 px-2 py-1" />
          <select value={department} onChange={e=>{setDepartment(e.target.value); setPage(1)}} className="rounded-md border border-slate-300 px-2 py-1">
            <option value="All">All Departments</option>
            {departments.map((d:any)=> <option key={d._id} value={d._id}>{d.name}</option>)}
          </select>
          <select value={doctor} onChange={e=>{setDoctor(e.target.value); setPage(1)}} className="rounded-md border border-slate-300 px-2 py-1">
            <option value="All">All Doctors</option>
            {doctors.map((d:any)=> <option key={d._id} value={d._id}>{d.name}</option>)}
          </select>
          <select value={tokenType} onChange={e=>{setTokenType(e.target.value as any); setPage(1)}} className="rounded-md border border-slate-300 px-2 py-1">
            <option value="All">All Types</option>
            <option value="Cash">Cash</option>
            <option value="Corporate">Corporate</option>
          </select>
          <select value={visitCategory} onChange={e=>{setVisitCategory(e.target.value as any); setPage(1)}} className="rounded-md border border-slate-300 px-2 py-1">
            <option value="All">All Categories</option>
            <option value="Public">Public</option>
            <option value="Private">Private</option>
          </select>
          <button className="rounded-md border border-slate-300 px-3 py-1.5 hover:bg-slate-50">Export CSV</button>
          <button onClick={exportPdf} className="rounded-md border border-slate-300 px-3 py-1.5 hover:bg-slate-50">Export PDF</button>
        </div>
      </div>

      <div className="mt-4">
        <input
          value={query}
          onChange={(e)=>{setQuery(e.target.value); setPage(1)}}
          placeholder="Search by name, token#, MR#, phone, doctor, department, age, gender, address, or time..."
          className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-200"
        />
      </div>

      <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <StatCard title="Date" value={from === to ? from : `${from} → ${to}`} tone="amber" />
        <StatCard title="Total Tokens" value={totalTokens} tone="green" />
        <StatCard title="Cash Revenue" value={`Rs. ${totalRevenue.toLocaleString()}`} tone="violet" />
        <StatCard title="Card Revenue" value={`Rs. ${cardRevenue.toLocaleString()}`} tone="indigo" />
        <StatCard title="Total Revenue" value={`Rs. ${totalRevenueAll.toLocaleString()}`} tone="green" />
        <StatCard title="Corporate Tokens" value={filtered.filter(r => r.isCorporate).length} tone="indigo" />
        <StatCard title="Discount (PKR)" value={`Rs. ${totalDiscount.toLocaleString()}`} tone="violet" />
        <StatCard title="Returned" value={returnedPatients} tone="amber" />
      </div>

      <div className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white">
        <table className="min-w-full divide-y divide-slate-200 text-sm">
          <thead className="bg-slate-50">
            <tr className="text-left text-slate-600">
              <Th>Date</Th>
              <Th>Time</Th>
              <Th>Type</Th>
              <Th>Token #</Th>
              <Th>MR #</Th>
              <Th>Patient</Th>
              <Th>Performed By</Th>
              <Th>Guardian</Th>
              <Th>CNIC</Th>
              <Th>Token Type</Th>
              <Th>Gender</Th>
              <Th>Phone</Th>
              <Th>Doctor</Th>
              <Th>Department</Th>
              <Th>Fee</Th>
              <Th>Discount</Th>
              <Th>Status</Th>
              <Th>Print</Th>
              <Th>Actions</Th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-200">
            {pageRows.map((r) => (
              <tr key={r._id} className={`text-slate-700 ${r.status === 'returned' ? 'bg-amber-50' : ''} ${r.isCorporate ? 'bg-violet-50/30' : ''}`}>
                <Td>{r.date}</Td>
                <Td>{r.time}</Td>
                <Td>
                  {r.isCorporate ? (
                    <span className="inline-flex rounded bg-violet-100 px-2 py-0.5 text-xs font-medium text-violet-700">Corporate</span>
                  ) : (
                    (String(r.paidMethod || 'Cash').toLowerCase() === 'bank' || String(r.paidMethod || '').toLowerCase() === 'card') ? (
                      <span className="inline-flex rounded bg-indigo-100 px-2 py-0.5 text-xs font-medium text-indigo-700">Card</span>
                    ) : (
                      <span className="inline-flex rounded bg-emerald-100 px-2 py-0.5 text-xs font-medium text-emerald-700">Cash</span>
                    )
                  )}
                </Td>
                <Td className="font-semibold">{r.tokenNo}</Td>
                <Td>{r.mrNo}</Td>
                <Td>{r.patient}</Td>
                <Td>{r.performedBy || '-'}</Td>
                <Td>{(r.guardianRel || r.guardianName) ? `${r.guardianRel ? r.guardianRel + ' ' : ''}${r.guardianName || ''}`.trim() : '-'}</Td>
                <Td>{r.cnic || '-'}</Td>
                <Td>
                  {r.visitCategory === 'private' ? (
                    <span className="inline-flex rounded bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-700">Private</span>
                  ) : (
                    <span className="inline-flex rounded bg-blue-100 px-2 py-0.5 text-xs font-medium text-blue-700">Public</span>
                  )}
                </Td>
                <Td>{r.gender || '-'}</Td>
                <Td>{r.phone || '-'}</Td>
                <Td>{r.doctor || '-'}</Td>
                <Td>{r.department || '-'}</Td>
                <Td>{r.fee.toFixed(0)}</Td>
                <Td>{(r.discount || 0).toFixed(0)}</Td>
                <Td>{r.status}</Td>
                <Td>
                  <div className="flex flex-col gap-1">
                    <button onClick={() => printSlip(r)} className="text-sky-600 hover:underline text-left">Print Slip</button>
                    <button onClick={() => printRx(r)} className="text-violet-700 hover:underline text-left">Print Rx</button>
                  </div>
                </Td>
                <Td>
                  <div className="flex items-center gap-2">
                    <button onClick={() => openEdit(r)} title="Edit" className="text-sky-600 hover:text-sky-800">✏️</button>
                    <button
                      disabled={actioningId === r._id}
                      onClick={() => setStatus(r, r.status === 'returned' ? 'queued' : 'returned')}
                      title={r.status === 'returned' ? 'Undo Return' : 'Return'}
                      className={`disabled:opacity-50 ${r.status === 'returned' ? 'text-amber-800 hover:text-amber-900' : 'text-amber-600 hover:text-amber-800'}`}
                    >
                      ↩️
                    </button>
                  </div>
                </Td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="flex items-center justify-between border-t border-slate-200 p-3 text-sm text-slate-700">
          <div className="flex items-center gap-2">
            <span>Rows per page</span>
            <select value={rowsPerPage} onChange={e=>{setRowsPerPage(parseInt(e.target.value)); setPage(1)}} className="rounded-md border border-slate-300 px-2 py-1">
              {[10,20,50].map(n => <option key={n} value={n}>{n}</option>)}
            </select>
          </div>
          <div>Page {page} of {totalPages}</div>
          <div className="flex items-center gap-2">
            <button disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))} className="rounded-md border border-slate-300 px-2 py-1 disabled:opacity-50">Prev</button>
            <button disabled={page>=totalPages} onClick={()=>setPage(p=>Math.min(totalPages,p+1))} className="rounded-md border border-slate-300 px-2 py-1 disabled:opacity-50">Next</button>
          </div>
        </div>
      </div>
      {showSlip && slipData && (
        <Hospital_TokenSlip open={showSlip} onClose={()=>setShowSlip(false)} data={slipData as TokenSlipData} autoPrint={false} />
      )}
      <Toast toast={toast} onClose={()=>setToast(null)} />
    </div>
  )
}

function Th({ children }: { children: ReactNode }) {
  return <th className="px-4 py-2 font-medium">{children}</th>
}
function Td({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <td className={`px-4 py-2 ${className}`}>{children}</td>
}

function StatCard({ title, value, tone }: { title: string; value: ReactNode; tone: 'blue'|'green'|'violet'|'amber'|'indigo' }) {
  const tones: Record<string, string> = {
    blue: 'bg-blue-50 text-blue-700 border-blue-100',
    green: 'bg-emerald-50 text-emerald-700 border-emerald-100',
    violet: 'bg-violet-50 text-violet-700 border-violet-100',
    amber: 'bg-amber-50 text-amber-700 border-amber-100',
    indigo: 'bg-indigo-50 text-indigo-700 border-indigo-100',
  }
  return (
    <div className={`rounded-xl border p-4 ${tones[tone]}`}>
      <div className="text-sm opacity-80">{title}</div>
      <div className="mt-1 text-xl font-semibold">{value}</div>
      <div className="text-xs opacity-60">Real-time data</div>
    </div>
  )
}
