import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { hospitalApi } from '../../utils/api'
import Hospital_TokenSlip from '../../components/hospital/Hospital_TokenSlip'
import Toast, { type ToastState } from '../../components/ui/Toast'
import { previewHospitalRxPdf } from '../../utils/hospitalRxPdf'

function escHtml(v: any){
  return String(v ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' } as any)[c] || c)
}

function buildTokensPdfHtml({
  title,
  printedAt,
  hospital,
  filters,
  rows,
}: {
  title: string
  printedAt: Date
  hospital: { name: string; address?: string; phone?: string; logoDataUrl?: string }
  filters: string
  rows: Array<{ time?: string; tokenNo?: string; mrNo?: string; patient?: string; phone?: string; doctor?: string; department?: string; fee?: any; isCorporate?: boolean; paidMethod?: string; status?: string }>
}){
  const printedDate = printedAt.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
  const printedTime = printedAt.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })
  const head = ['Time','Type','Token #','MR #','Patient','Phone','Doctor','Department','Fee','Status']
  const th = head.map(h => `<th>${escHtml(h)}</th>`).join('')
  const body = (rows || []).map(r => {
    const method = String(r.paidMethod || '').toLowerCase()
    const t = r.isCorporate ? 'Corporate' : (method === 'bank' || method === 'card' ? 'Card' : 'Cash')
    const fee = Number(r.fee || 0)
    return `<tr>
      <td>${escHtml(r.time || '')}</td>
      <td>${escHtml(t)}</td>
      <td>${escHtml(r.tokenNo || '')}</td>
      <td>${escHtml(r.mrNo || '')}</td>
      <td>${escHtml(r.patient || '')}</td>
      <td>${escHtml(r.phone || '')}</td>
      <td>${escHtml(r.doctor || '')}</td>
      <td>${escHtml(r.department || '')}</td>
      <td class="right">${escHtml(`Rs ${fee.toFixed(0)}`)}</td>
      <td>${escHtml(r.status || '')}</td>
    </tr>`
  }).join('')
  const empty = `<tr><td class="empty" colspan="${head.length}">No rows</td></tr>`

  return `<!doctype html>
  <html>
    <head>
      <meta charset="utf-8"/>
      <title>${escHtml(title)}</title>
      <style>
        @page { size: A4 landscape; margin: 10mm }
        *{ box-sizing:border-box }
        body{ font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial; color:#0f172a; line-height:1.35; font-size:11px }
        .header{ border:1px solid #e2e8f0; border-radius:10px; padding:12px; margin-bottom:10px }
        .hdr{ display:grid; grid-template-columns: 70px 1fr 70px; align-items:center; gap:10px }
        .logo{ width:60px; height:60px; object-fit:contain }
        .hname{ font-size:16px; font-weight:800; text-align:center }
        .hmeta{ font-size:11px; text-align:center; color:#475569 }
        .title{ margin-top:8px; font-size:14px; font-weight:800 }
        .meta{ margin-top:4px; display:flex; justify-content:space-between; gap:12px; color:#334155 }
        table{ width:100%; border-collapse:collapse; table-layout:fixed }
        th,td{ border:1px solid #e2e8f0; padding:6px 6px; vertical-align:top; word-wrap:break-word }
        th{ background:#f8fafc; font-weight:800; color:#334155 }
        td.right, th.right{ text-align:right }
        .empty{ text-align:center; color:#64748b; padding:10px }
        .footer{ margin-top:10px; color:#94a3b8; font-size:10px; text-align:center }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="hdr">
          <div>${hospital.logoDataUrl ? `<img class="logo" src="${hospital.logoDataUrl}" />` : ''}</div>
          <div>
            <div class="hname">${escHtml(hospital.name || 'Hospital')}</div>
            <div class="hmeta">${escHtml(hospital.address || '')}${hospital.phone ? ` • Ph: ${escHtml(hospital.phone)}` : ''}</div>
          </div>
          <div></div>
        </div>
        <div class="title">${escHtml(title)}</div>
        <div class="meta">
          <div><b>Filters:</b> ${escHtml(filters || '-')}</div>
          <div><b>Printed:</b> ${escHtml(printedDate)} ${escHtml(printedTime)}</div>
        </div>
      </div>

      <table>
        <thead><tr>${th}</tr></thead>
        <tbody>${body || empty}</tbody>
      </table>

      <div class="footer">Generated by Hospital Management System</div>
    </body>
  </html>`
}

type TokenSlipData = {
  tokenNo: string
  departmentName: string
  doctorName: string
  patientName: string
  phone?: string
  mrn?: string
  age?: string
  gender?: string
  amount: number
  discount: number
  payable: number
  createdAt?: string
  fbr?: any
}

interface TokenRow {
  _id: string
  time: string
  tokenNo: string
  mrNo: string
  patient: string
  portal?: string
  visitCategory?: 'public' | 'private'
  gender?: string
  phone?: string
  doctor?: string
  department?: string
  fee: number
  discount: number
  status: 'queued'|'in-progress'|'completed'|'returned'|'cancelled'
  paidMethod?: 'Cash'|'Bank'|'AR'|string
  isCorporate?: boolean
  corporateId?: string
  performedBy?: string
  createdAt?: string
  patientUpload?: {
    fileName?: string
    mimeType?: string
    dataBase64?: string
    uploadedAt?: string
  }
}

export default function Hospital_TodayTokens(){
  const navigate = useNavigate()
  const [rows, setRows] = useState<TokenRow[]>([])
  const [query, setQuery] = useState('')
  const [departmentId, setDepartmentId] = useState<string>('All')
  const [doctorId, setDoctorId] = useState<string>('All')
  const [departments, setDepartments] = useState<any[]>([])
  const [doctors, setDoctors] = useState<any[]>([])
  const [revByMethod, setRevByMethod] = useState<{ cash: number; card: number }>({ cash: 0, card: 0 })
  const [rowsPerPage, setRowsPerPage] = useState(10)
  const [page, setPage] = useState(1)
  const [showSlip, setShowSlip] = useState(false)
  const [slipData, setSlipData] = useState<TokenSlipData | null>(null)
  const [actioningId, setActioningId] = useState<string>('')
  const [toast, setToast] = useState<ToastState>(null)
  const [confirmCancel, setConfirmCancel] = useState<{ open: boolean; token: any } | null>(null)
  const [viewImage, setViewImage] = useState<{ url: string; title: string } | null>(null)
  const [viewPatient, setViewPatient] = useState<TokenRow | null>(null)
  const [tokenType, setTokenType] = useState<'All' | 'Cash' | 'Corporate'>('All')
  const [visitCategory, setVisitCategory] = useState<'All' | 'Public' | 'Private'>('All')

  async function onPrintSlip(row: TokenRow) {
    printSlip(row)
  }

  async function onPrintRx(row: TokenRow) {
    printRx(row)
  }


  useEffect(() => {
    ;(async()=>{
      try {
        const [deps, docs] = await Promise.all([
          hospitalApi.listDepartments() as any,
          hospitalApi.listDoctors() as any,
        ])
        setDepartments(deps?.departments || deps?.data || deps || [])
        setDoctors(docs?.doctors || docs?.data || docs || [])
      } catch {
        setDepartments([])
        setDoctors([])
      }
    })()
  }, [])

  useEffect(() => { load() }, [departmentId, doctorId, tokenType, visitCategory])

  async function load(){
    const toLocalIso = (d: Date) => {
      const x = new Date(d)
      x.setMinutes(x.getMinutes() - x.getTimezoneOffset())
      return x.toISOString().slice(0, 10)
    }
    const today = toLocalIso(new Date())

    const params: any = { date: today }
    console.log('TodayTokens loading with date:', today, 'params:', params)
    if (departmentId !== 'All') params.departmentId = departmentId
    if (doctorId !== 'All') params.doctorId = doctorId
    const res = await hospitalApi.listTokens(params) as any
    console.log('TodayTokens API response:', res)
    const items: TokenRow[] = (res.tokens || []).map((t: any) => ({
      _id: t._id,
      time: t.createdAt ? new Date(t.createdAt).toLocaleTimeString() : '',
      tokenNo: t.tokenNo,
      mrNo: t.patientId?.mrn || t.mrn || '-',
      patient: t.patientId?.fullName || t.patientName || '-',
      portal: t.portal,
      visitCategory: t.visitCategory,
      gender: t.patientId?.gender,
      phone: t.patientId?.phoneNormalized,
      doctor: t.doctorId?.name || '-',
      department: t.departmentId?.name || '-',
      fee: Number(t.fee || 0),
      discount: Number(t.discount || 0),
      status: t.status,
      paidMethod: t.paidMethod || t.paymentMethod || t.method,
      isCorporate: !!t.corporateId,
      corporateId: t.corporateId,
      performedBy: t.createdByUsername || t.createdBy || '-',
      createdAt: t.createdAt,
      patientUpload: t.patientUpload,
    }))
    console.log('TodayTokens mapped items:', items)
    const rowsClean = items.filter(r => {
      if (r.status === 'cancelled') return false
      // Hide patient-portal appointments from Today's Tokens - they should only appear in Hospital Appointments page
      if (r.portal === 'patient') {
        console.log('Filtering out patient portal token:', r)
        return false
      }
      return true
    })
    console.log('TodayTokens after filtering:', rowsClean)
    setRows(rowsClean)
    setPage(1)

    // Revenue split from tokens based on selected payment method at token creation
    let cash = 0
    let card = 0
    for (const r of rowsClean){
      if (r.status === 'returned') continue
      if (r.isCorporate) continue
      const amt = Number(r.fee || 0)
      if (!isFinite(amt) || amt <= 0) continue
      const method = String(r.paidMethod || 'Cash').toLowerCase()
      if (method === 'cash') cash += amt
      else if (method === 'bank' || method === 'card') card += amt
      else card += amt
    }
    setRevByMethod({ cash, card })
  }

  const filtered = useMemo(() => {
    let result = rows

    if (tokenType !== 'All'){
      result = result.filter(r => {
        if (tokenType === 'Corporate') return !!r.isCorporate
        if (tokenType === 'Cash') return !r.isCorporate
        return true
      })
    }

    if (visitCategory !== 'All'){
      result = result.filter(r => {
        if (visitCategory === 'Public') return r.visitCategory !== 'private'
        if (visitCategory === 'Private') return r.visitCategory === 'private'
        return true
      })
    }

    const q = query.trim().toLowerCase()
    if (!q) return result
    return result.filter(r =>
      [r.patient, r.mrNo, r.tokenNo, r.phone, r.doctor, r.department, r.gender, r.time]
        .filter(Boolean)
        .some(v => String(v).toLowerCase().includes(q))
    )
  }, [query, rows, tokenType, visitCategory])

  const revenueRows = useMemo(() => filtered.filter(r => r.status !== 'returned' && !r.isCorporate), [filtered])

  const totalTokens = filtered.length
  const totalRevenue = revByMethod.cash
  const cardRevenue = revByMethod.card
  const totalRevenueAll = revByMethod.cash + revByMethod.card
  const totalDiscount = revenueRows.reduce((s, r) => s + (r.discount || 0), 0)
  const discountTokens = revenueRows.filter(r => (r.discount || 0) > 0).length
  const returnedPatients = filtered.filter(r => r.status === 'returned').length

  const start = (page - 1) * rowsPerPage
  const pageRows = filtered.slice(start, start + rowsPerPage)
  const totalPages = Math.max(1, Math.ceil(filtered.length / rowsPerPage))

  async function setStatus(row: TokenRow, status: TokenRow['status']){
    try{
      setActioningId(row._id)
      await hospitalApi.updateTokenStatus(row._id, status)
      await load()
    } catch (e: any){
      setToast({ type: 'error', message: e?.message || 'Failed to update status' })
    } finally {
      setActioningId('')
    }
  }

  function printSlip(r: TokenRow){
    const slip: TokenSlipData = {
      tokenNo: r.tokenNo,
      departmentName: r.department || '-',
      doctorName: r.doctor || '-',
      patientName: r.patient || '-',
      phone: r.phone || '',
      mrn: r.mrNo || '',
      gender: r.gender,
      amount: r.fee + (r.discount || 0),
      discount: r.discount || 0,
      payable: r.fee,
      createdAt: r.createdAt,
    }
    setSlipData(slip)
    setShowSlip(true)
  }

  async function printRx(r: TokenRow){
    try{
      const s: any = await hospitalApi.getSettings()
      await previewHospitalRxPdf({
        settings: {
          name: s?.settings?.name || s?.name,
          address: s?.settings?.address || s?.address,
          phone: s?.settings?.phone || s?.phone,
          logoDataUrl: s?.settings?.logoDataUrl || s?.logoDataUrl,
        },
        doctor: { name: r.doctor || '-', departmentName: r.department || '-' },
        patient: {
          name: r.patient || '-',
          mrn: r.mrNo || '-',
          gender: r.gender,
          phone: r.phone,
        },
        items: [],
        createdAt: new Date().toISOString(),
        tokenNo: r.tokenNo,
      } as any)
    } catch (e: any){
      setToast({ type: 'error', message: e?.message || 'Failed to open Rx preview' })
    }
  }

  function openEdit(r: TokenRow){
    // Stay on current portal (reception or hospital)
    const portal = window.location.pathname.startsWith('/reception') ? 'reception' : 'hospital'
    navigate(`/${portal}/token-generator?tokenId=${encodeURIComponent(r._id)}`)
  }

  

  // No index mapping needed when actions use row ids

  const exportCSV = () => {
    const cols = ['Time','Token #','MR #','Patient','Gender','Phone','Doctor','Department','Fee','Returned']
    const lines = [cols.join(',')]
    for (const r of filtered) {
      lines.push([
        r.time,
        r.tokenNo,
        r.mrNo,
        r.patient,
        r.gender ?? '',
        r.phone ?? '',
        r.doctor ?? '',
        r.department ?? '',
        r.fee,
        r.status === 'returned' ? 'Yes' : 'No',
      ].map(v => typeof v === 'string' && v.includes(',') ? `"${v.replace(/"/g,'""')}"` : String(v)).join(','))
    }
    const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `todays-tokens-${new Date().toISOString().slice(0,10)}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  const exportPdf = async () => {
    try{
      const api = (window as any).electronAPI
      if (!api || typeof api.printPreviewHtml !== 'function'){
        setToast({ type: 'error', message: 'PDF export is only available in the desktop app' })
        return
      }
      const s: any = await hospitalApi.getSettings().catch(()=>({}))
      const hospital = {
        name: s?.settings?.name || s?.name || 'Hospital',
        address: s?.settings?.address || s?.address || '',
        phone: s?.settings?.phone || s?.phone || '',
        logoDataUrl: s?.settings?.logoDataUrl || s?.logoDataUrl || '',
      }

      const depName = departmentId === 'All'
        ? 'All Departments'
        : (departments.find((d:any)=> String(d._id||d.id) === String(departmentId))?.name || 'Department')
      const docName = doctorId === 'All'
        ? 'All Doctors'
        : (doctors.find((d:any)=> String(d._id||d.id) === String(doctorId))?.name || 'Doctor')

      const filters = `Date: ${new Date().toISOString().slice(0,10)}  •  Dept: ${depName}  •  Doctor: ${docName}  •  Type: ${tokenType}  •  Category: ${visitCategory}`

      const htmlDoc = buildTokensPdfHtml({
        title: "Today's Tokens",
        printedAt: new Date(),
        hospital,
        filters,
        rows: filtered.map(r => ({
          time: r.time,
          tokenNo: r.tokenNo,
          mrNo: r.mrNo,
          patient: r.patient,
          phone: r.phone,
          doctor: r.doctor,
          department: r.department,
          fee: r.fee,
          isCorporate: r.isCorporate,
          paidMethod: r.paidMethod as any,
          status: r.status,
        })),
      })

      const r = await api.printPreviewHtml(htmlDoc, { printBackground: true, marginsType: 0 })
      if (r && r.ok === false) setToast({ type: 'error', message: r.error || 'Failed to generate PDF' })
    }catch(e: any){
      setToast({ type: 'error', message: e?.message || 'Failed to generate PDF' })
    }
  }

  return (
    <div>
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <h2 className="text-xl font-semibold text-slate-800">Today's Tokens <span className="ml-1 rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">{filtered.length}</span></h2>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={exportCSV} className="rounded-md border border-slate-300 px-3 py-1.5 text-sm hover:bg-slate-50">Export CSV</button>
          <button onClick={exportPdf} className="rounded-md border border-slate-300 px-3 py-1.5 text-sm hover:bg-slate-50">Export PDF</button>
        </div>
      </div>

      <div className="mt-4">
        <input
          value={query}
          onChange={(e)=>{ setQuery(e.target.value); setPage(1) }}
          placeholder="Search by name, token#, MR#, phone, doctor, department, age, gender, address, or time..."
          className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-200"
        />
      </div>

      <div className="mt-3 flex flex-wrap items-center gap-2 text-sm">
        <select value={departmentId} onChange={e=>{ setDepartmentId(e.target.value); setPage(1) }} className="rounded-md border border-slate-300 px-2 py-1">
          <option value="All">All Departments</option>
          {departments.map((d:any) => (
            <option key={String(d._id || d.id)} value={String(d._id || d.id)}>{d.name}</option>
          ))}
        </select>
        <select value={doctorId} onChange={e=>{ setDoctorId(e.target.value); setPage(1) }} className="rounded-md border border-slate-300 px-2 py-1">
          <option value="All">All Doctors</option>
          {doctors.map((d:any) => (
            <option key={String(d._id || d.id)} value={String(d._id || d.id)}>{d.name}</option>
          ))}
        </select>
        <select value={tokenType} onChange={e=>{ setTokenType(e.target.value as any); setPage(1) }} className="rounded-md border border-slate-300 px-2 py-1">
          <option value="All">All Types</option>
          <option value="Cash">Cash</option>
          <option value="Corporate">Corporate</option>
        </select>
        <select value={visitCategory} onChange={e=>{ setVisitCategory(e.target.value as any); setPage(1) }} className="rounded-md border border-slate-300 px-2 py-1">
          <option value="All">All Categories</option>
          <option value="Public">Public</option>
          <option value="Private">Private</option>
        </select>
      </div>

      <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <StatCard title="Tokens Generated" value={totalTokens} tone="green" />
        <StatCard title="Cash Revenue" value={`Rs. ${totalRevenue.toLocaleString()}`} tone="violet" />
        <StatCard title="Card Revenue" value={`Rs. ${cardRevenue.toLocaleString()}`} tone="indigo" />
        <StatCard title="Total Revenue" value={`Rs. ${totalRevenueAll.toLocaleString()}`} tone="green" />
        <StatCard title="Corporate Tokens" value={filtered.filter(r => r.isCorporate).length} tone="indigo" />
        <StatCard title="Discount (PKR)" value={`Rs. ${totalDiscount.toLocaleString()}`} tone="violet" />
        <StatCard title="Discounted Tokens" value={discountTokens} tone="green" />
        <StatCard title="Returned Patients" value={returnedPatients} tone="amber" />
      </div>

      <div className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white">
        <table className="min-w-full divide-y divide-slate-200 text-sm">
          <thead className="bg-slate-50">
            <tr className="text-left text-slate-600">
              <Th>Time</Th>
              <Th>Type</Th>
              <Th>Token #</Th>
              <Th>MR #</Th>
              <Th>Patient</Th>
              <Th>Performed By</Th>
              <Th>Token Type</Th>
              <Th>Gender</Th>
              <Th>Phone</Th>
              <Th>Doctor</Th>
              <Th>Department</Th>
              <Th>Fee</Th>
              <Th>Billing Type</Th>
              <Th>Print</Th>
              <Th>Actions</Th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-200">
            {pageRows.map((r) => (
              <tr key={r._id} className={`text-slate-700 ${r.status === 'returned' ? 'bg-amber-50' : ''} ${r.isCorporate ? 'bg-violet-50/30' : ''}`}>
                <Td>{r.time}</Td>
                <Td>
                  {r.isCorporate ? (
                    <span className="inline-flex rounded bg-violet-100 px-2 py-0.5 text-xs font-medium text-violet-700">Corporate</span>
                  ) : (
                    (String(r.paidMethod || 'Cash').toLowerCase() === 'bank' || String(r.paidMethod || '').toLowerCase() === 'card') ? (
                      <span className="inline-flex rounded bg-indigo-100 px-2 py-0.5 text-xs font-medium text-indigo-700">Card</span>
                    ) : (
                      <span className="inline-flex rounded bg-emerald-100 px-2 py-0.5 text-xs font-medium text-emerald-700">Cash</span>
                    )
                  )}
                </Td>
                <Td>{r.tokenNo}</Td>
                <Td>{r.mrNo}</Td>
                <Td className="font-medium">{r.patient}</Td>
                <Td>{r.performedBy || '-'}</Td>
                <Td>
                  {r.visitCategory === 'private' ? (
                    <span className="inline-flex rounded bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-700">Private</span>
                  ) : (
                    <span className="inline-flex rounded bg-blue-100 px-2 py-0.5 text-xs font-medium text-blue-700">Public</span>
                  )}
                </Td>
                <Td>{r.gender}</Td>
                <Td>{r.phone || '-'}</Td>
                <Td>{r.doctor || '-'}</Td>
                <Td>{r.department || '-'}</Td>
                <Td className="font-semibold text-emerald-600">Rs. {r.fee.toLocaleString()}</Td>
                <Td>{r.paidMethod || 'Cash'}</Td>
                <Td>
                  <div className="flex flex-col gap-1">
                    <button onClick={()=>onPrintSlip(r)} className="cursor-pointer text-sky-600 hover:underline text-left">Print Slip</button>
                    <button onClick={()=>onPrintRx(r)} className="cursor-pointer text-violet-700 hover:underline text-left">Print Rx</button>
                  </div>
                </Td>
                <Td>
                  <div className="flex gap-2">
                    <button disabled={actioningId===r._id} onClick={()=>openEdit(r)} title="Edit" className="cursor-pointer text-sky-600 hover:text-sky-800 disabled:opacity-50">✏️</button>
                    <button disabled={actioningId===r._id} onClick={()=>setStatus(r, r.status === 'returned' ? 'queued' : 'returned')} title="Return" className={`cursor-pointer hover:text-amber-800 ${r.status === 'returned' ? 'text-amber-800' : 'text-amber-600'} disabled:opacity-50`}>↩️</button>
                    <button disabled={actioningId===r._id} onClick={()=>setConfirmCancel({ open: true, token: r })} title="Cancel" className="cursor-pointer text-rose-600 hover:text-rose-800 disabled:opacity-50">🗑️</button>

                    {r?.patientUpload?.dataBase64 ? (
                      <img
                        src={`data:${String(r?.patientUpload?.mimeType || 'image/*')};base64,${String(r?.patientUpload?.dataBase64 || '')}`}
                        alt="upload"
                        onClick={() => setViewImage({
                          url: `data:${String(r?.patientUpload?.mimeType || 'image/*')};base64,${String(r?.patientUpload?.dataBase64 || '')}`,
                          title: String(r?.patientUpload?.fileName || 'Upload')
                        })}
                        className="h-12 w-12 cursor-pointer rounded-md border border-slate-200 object-cover hover:opacity-80 transition-opacity"
                      />
                    ) : null}
                  </div>
                </Td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="flex items-center justify-between border-t border-slate-200 p-3 text-sm text-slate-700">
          <div className="flex items-center gap-2">
            <span>Rows per page</span>
            <select value={rowsPerPage} onChange={e=>{setRowsPerPage(parseInt(e.target.value)); setPage(1)}} className="rounded-md border border-slate-300 px-2 py-1">
              {[10,20,50].map(n => <option key={n} value={n}>{n}</option>)}
            </select>
          </div>
          <div>Page {page} of {totalPages}</div>
          <div className="flex items-center gap-2">
            <button disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))} className="rounded-md border border-slate-300 px-2 py-1 disabled:opacity-50">Prev</button>
            <button disabled={page>=totalPages} onClick={()=>setPage(p=>Math.min(totalPages,p+1))} className="rounded-md border border-slate-300 px-2 py-1 disabled:opacity-50">Next</button>
          </div>
        </div>
      </div>

      {showSlip && slipData && (
        <Hospital_TokenSlip open={showSlip} onClose={()=>setShowSlip(false)} data={slipData} autoPrint={false} />
      )}

      {viewImage && (
        <div 
          className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 p-4"
          onClick={() => setViewImage(null)}
        >
          <div className="relative max-h-full max-w-4xl overflow-hidden rounded-2xl bg-white p-2 shadow-2xl" onClick={e => e.stopPropagation()}>
            <div className="absolute right-4 top-4 z-10">
              <button 
                onClick={() => setViewImage(null)}
                className="flex h-10 w-10 items-center justify-center rounded-full bg-black/20 text-white hover:bg-black/40 transition-colors"
              >
                ✕
              </button>
            </div>
            <img 
              src={viewImage.url} 
              alt={viewImage.title} 
              className="max-h-[85vh] w-auto rounded-xl object-contain shadow-lg"
            />
            <div className="mt-2 px-2 py-1 text-center text-sm font-semibold text-slate-700">
              {viewImage.title}
            </div>
          </div>
        </div>
      )}

      {confirmCancel?.open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
          <div className="w-full max-w-md overflow-hidden rounded-xl bg-white shadow-2xl ring-1 ring-black/5">
            <div className="border-b border-slate-200 px-5 py-3 font-semibold text-slate-800">Confirm</div>
            <div className="px-5 py-4 text-sm text-slate-700">Cancel (delete) this token?</div>
            <div className="flex items-center justify-end gap-2 border-t border-slate-200 px-5 py-3">
              <button type="button" onClick={()=>setConfirmCancel(null)} className="btn-outline-navy">No</button>
              <button
                type="button"
                onClick={async()=>{
                  if (!confirmCancel?.token) return
                  await setStatus(confirmCancel.token, 'cancelled')
                  setConfirmCancel(null)
                }}
                className="rounded-lg bg-rose-600 px-4 py-2 text-sm font-semibold text-white hover:bg-rose-700"
              >
                Yes, Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      {viewPatient && (
        <div className="fixed inset-0 z-[120] flex items-center justify-center bg-black/40 p-4">
          <div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl ring-1 ring-black/5">
            <div className="flex items-center justify-between border-b border-slate-100 pb-4">
              <h2 className="text-xl font-bold text-slate-900">Patient Details</h2>
              <button onClick={() => setViewPatient(null)} className="text-slate-400 hover:text-slate-600">✕</button>
            </div>
            <div className="mt-6 grid grid-cols-2 gap-y-4 text-sm">
              <div>
                <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Patient Name</div>
                <div className="mt-1 font-medium text-slate-900">{viewPatient.patient}</div>
              </div>
              <div>
                <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider">MR#</div>
                <div className="mt-1 font-medium text-slate-900">{viewPatient.mrNo}</div>
              </div>
              <div>
                <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Phone</div>
                <div className="mt-1 font-medium text-slate-900">{viewPatient.phone || '-'}</div>
              </div>
              <div>
                <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Gender</div>
                <div className="mt-1 font-medium text-slate-900">{viewPatient.gender || '-'}</div>
              </div>
              <div>
                <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Doctor</div>
                <div className="mt-1 font-medium text-slate-900">{viewPatient.doctor}</div>
              </div>
              <div>
                <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Department</div>
                <div className="mt-1 font-medium text-slate-900">{viewPatient.department}</div>
              </div>
              <div>
                <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Consultant Fee</div>
                <div className="mt-1 font-medium text-emerald-600 font-bold">Rs. {viewPatient.fee.toLocaleString()}</div>
              </div>
              <div>
                <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Billing Type</div>
                <div className="mt-1 font-medium text-slate-900">{viewPatient.paidMethod || 'Cash'}</div>
              </div>
              {viewPatient.patientUpload?.dataBase64 && (
                <div className="col-span-2 mt-2">
                  <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Payment Proof</div>
                  <img 
                    src={`data:${viewPatient.patientUpload.mimeType || 'image/*'};base64,${viewPatient.patientUpload.dataBase64}`} 
                    className="max-h-48 w-full rounded-xl object-contain border border-slate-100"
                    alt="Proof"
                  />
                </div>
              )}
            </div>
            <div className="mt-8 flex justify-end pt-4 border-t border-slate-100">
              <button
                onClick={() => setViewPatient(null)}
                className="rounded-xl bg-slate-900 px-6 py-2 text-sm font-bold text-white hover:bg-slate-800 transition-colors"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      <Toast toast={toast} onClose={()=>setToast(null)} />

    </div>
  )
}

function Th({ children }: { children: React.ReactNode }) {
  return <th className="px-4 py-2 font-medium">{children}</th>
}
function Td({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <td className={`px-4 py-2 ${className}`}>{children}</td>
}

function StatCard({ title, value, tone }: { title: string; value: React.ReactNode; tone: 'blue'|'green'|'violet'|'amber'|'indigo' }) {
  const tones: Record<string, string> = {
    blue: 'bg-blue-50 text-blue-700 border-blue-100',
    green: 'bg-emerald-50 text-emerald-700 border-emerald-100',
    violet: 'bg-violet-50 text-violet-700 border-violet-100',
    amber: 'bg-amber-50 text-amber-700 border-amber-100',
    indigo: 'bg-indigo-50 text-indigo-700 border-indigo-100',
  }
  return (
    <div className={`rounded-xl border p-4 ${tones[tone]}`}>
      <div className="text-sm text-slate-600 dark:text-slate-300 dark:opacity-100 opacity-80">{title}</div>
      <div className="mt-1 text-xl font-semibold text-slate-900 dark:text-slate-100">{value}</div>
      <div className="text-xs text-slate-500 dark:text-slate-400">Real-time data</div>
    </div>
  )
}
